### ISSUE TITLE
[Bug Report] Invoice Download Exception

### ISSUE THREAD

**Issue by rkm7232** [irontec/ivozprovider#1214]
### Description
When I create an invoice and click on download icon, this exception occures:
```
Dec 08 16:00:31 Debian klear[85167]: Cannot send headers; headers already sent in /opt/irontec/klear/library/Iron/Controller/Action/Helper/SendFileToClient.php, line 71 (0) # /usr/share/php/Zend/Controller/Response/Abstract.php(323)
Dec 08 16:00:31 Debian klear[85167]: Error: Uncaught Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /opt/irontec/klear/library/Iron/Controller/Action/Helper/SendFileToClient.php, line 71 in /usr/share/php/Zend/Controller/Response/Abstract.php:323
                                     Stack trace:
                                     #0 /usr/share/php/Zend/Controller/Response/Abstract.php(341): Zend_Controller_Response_Abstract->canSendHeaders(true)
                                     #1 /usr/share/php/Zend/Controller/Response/Abstract.php(768): Zend_Controller_Response_Abstract->sendHeaders()
                                     #2 /usr/share/php/Zend/Controller/Front.php(992): Zend_Controller_Response_Abstract->sendResponse()
                                     #3 /usr/share/php/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
                                     #4 /usr/share/php/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
                                     #5 /opt/irontec/ivozprovider/web/admin/public/zf.php(40): Zend_Application->run()
                                     #6 /opt/irontec/ivozprovider/web/admin/public/index.php(12): require('/opt/irontec/iv...')
                                     #7 {main}
                                       thrown (0) # /usr/share/php/Zend/Controller/Response/Abstract.php(323)
```

It seems the file download is working correctly (I created a file on VM and download it trough the download icon, then checked the file content)

this is the invoice content that I received from web/admin: 
```
%PDF-1.4
1 0 obj
<<
/Title (‏ے)
/Creator (‏ے w k h t m l t o p d f   0 . 1 2 . 3)
/Producer (‏ے Q t   4 . 8 . 7)
/CreationDate (D:20191206025823-05'00')
>>
endobj
3 0 obj
<<
/Type /ExtGState
/SA true
/SM 0.02
/ca 1.0
/CA 1.0
/AIS false
/SMask /None>>
endobj
4 0 obj
[/Pattern /DeviceRGB]
endobj
6 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
5 0 obj
<<
/Type /Page
/Parent 2 0 R
/Contents 7 0 R
/Resources 9 0 R
/Annots 10 0 R
/MediaBox [0 0 595 842]
>>
endobj
9 0 obj
<<
/ColorSpace <<
/PCSp 4 0 R
/CSp /DeviceRGB
/CSpg /DeviceGray
>>
/ExtGState <<
/GSa 3 0 R
>>
/Pattern <<
>>
/Font <<
>>
/XObject <<
>>
>>
endobj
10 0 obj
[ ]
endobj
7 0 obj
<<
/Length 8 0 R
/Filter /FlateDecode
>>
stream
xœ¥O»
1ى÷+¶جKŒ¹:…`!„b!ٌأ‏¾›ى	ل°»
dwf‡ةDîمï#Jكک¦î#(رYإ…ه¬[آ8±ëj،سaکM=dج ذ]z†ں+{Œi ةï3رiْ ء،'‍/شn“Eô°µJTGًصB§­p4iC¼ڑأ"~ہi…هPuS–ڑ³ج0E_uءOَپià “ZB
endstream
endobj
8 0 obj
166
endobj
2 0 obj
<<
/Type /Pages
/Kids 
[
5 0 R
]
/Count 1
/ProcSet [/PDF /Text /ImageB /ImageC]
>>
endobj
xref
0 11
0000000000 65535 f 
0000000009 00000 n 
0000000897 00000 n 
0000000163 00000 n 
0000000258 00000 n 
0000000344 00000 n 
0000000295 00000 n 
0000000638 00000 n 
0000000878 00000 n 
0000000463 00000 n 
0000000618 00000 n 
trailer
<<
/Size 11
/Info 1 0 R
/Root 6 0 R
>>
startxref
995
%%EOF
<br />
<b>Fatal error</b>:  Uncaught Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /opt/irontec/klear/library/Iron/Controller/Action/Helper/SendFileToClient.php, line 71 in /usr/share/php/Zend/Controller/Response/Abstract.php:323
Stack trace:
#0 /usr/share/php/Zend/Controller/Response/Abstract.php(341): Zend_Controller_Response_Abstract-&gt;canSendHeaders(true)
#1 /usr/share/php/Zend/Controller/Response/Abstract.php(768): Zend_Controller_Response_Abstract-&gt;sendHeaders()
#2 /usr/share/php/Zend/Controller/Front.php(992): Zend_Controller_Response_Abstract-&gt;sendResponse()
#3 /usr/share/php/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front-&gt;dispatch()
#4 /usr/share/php/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#5 /opt/irontec/ivozprovider/web/admin/public/zf.php(40): Zend_Application-&gt;run()
#6 /opt/irontec/ivozprovider/web/admin/public/index.php(12): require('/opt/irontec/iv...')
#7 {main}
  thrown in <b>/usr/share/php/Zend/Controller/Response/Abstract.php</b> on line <b>323</b><br />
```
---

- IvozProvider version: 2.13~2.13.0~201911

- Related sections:
    - [X] Billing & Invoicing
    - [X] Web Interface

### Troubleshooting
logs from journal added above.

**Comment by rkm7232** [comment]
Hi, thanks

How can I test it? I added that line to code but nothing changed.

After adding some exceptions and commenting the code I see no change in code behaviour.
Is there any cache I should remove? or anything else...

**Comment by rkm7232** [comment]
I added the generated invoice because I think the  generated pdf file is empty. I have a fixed cost in the invoice at least.

```
%PDF-1.4
1 0 obj
<<
/Title (‏ے)
/Creator (‏ے w k h t m l t o p d f   0 . 1 2 . 3)
/Producer (‏ے Q t   4 . 8 . 7)
/CreationDate (D:20191209132109-05'00')
>>
endobj
3 0 obj
<<
/Type /ExtGState
/SA true
/SM 0.02
/ca 1.0
/CA 1.0
/AIS false
/SMask /None>>
endobj
4 0 obj
[/Pattern /DeviceRGB]
endobj
6 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
5 0 obj
<<
/Type /Page
/Parent 2 0 R
/Contents 7 0 R
/Resources 9 0 R
/Annots 10 0 R
/MediaBox [0 0 595 842]
>>
endobj
9 0 obj
<<
/ColorSpace <<
/PCSp 4 0 R
/CSp /DeviceRGB
/CSpg /DeviceGray
>>
/ExtGState <<
/GSa 3 0 R
>>
/Pattern <<
>>
/Font <<
>>
/XObject <<
>>
>>
endobj
10 0 obj
[ ]
endobj
7 0 obj
<<
/Length 8 0 R
/Filter /FlateDecode
>>
stream
xœ¥O»
1ى÷+¶جKŒ¹:…`!„b!ٌأ‏¾›ى	ل°»
dwf‡ةDîمï#Jكک¦î#(رYإ…ه¬[آ8±ëj،سaکM=dج ذ]z†ں+{Œi ةï3رiْ ء،'‍/شn“Eô°µJTGًصB§­p4iC¼ڑأ"~ہi…هPuS–ڑ³ج0E_uءOَپià “ZB
endstream
endobj
8 0 obj
166
endobj
2 0 obj
<<
/Type /Pages
/Kids 
[
5 0 R
]
/Count 1
/ProcSet [/PDF /Text /ImageB /ImageC]
>>
endobj
xref
0 11
0000000000 65535 f 
0000000009 00000 n 
0000000897 00000 n 
0000000163 00000 n 
0000000258 00000 n 
0000000344 00000 n 
0000000295 00000 n 
0000000638 00000 n 
0000000878 00000 n 
0000000463 00000 n 
0000000618 00000 n 
trailer
<<
/Size 11
/Info 1 0 R
/Root 6 0 R
>>
startxref
995
%%EOF
```

**Comment by mmadariaga** [comment]
Hi @rkm7232,

> I added that line to code but nothing changed.

Are you still getting `headers already sent` exception? I was getting that exception as well but the invoices were created and downloaded correctly.

Please checkout /opt/irontec/ivozprovider/storage/ivozprovider_model_invoice.pdf/ directory, you'll see a tree like:
```                                                                                                                                                                                                               
└── 4                                                                                                                                                                                                                                 
    ├── 44                                                                                                                                                                                                                            
    ├── 45                                                                                                                                                                                                                            
    ├── 46                                                                                                                                                                                                                            
    ├── 47                                                                                                                                                                                                                            
    ├── 48                                                                                                                                                                                                                            
    └── 49   
```
44, 45, 46... are the invoices, copy one of them and add .pdf extension. If pdf content is empty (and you've calls on that time period / company) you've invoice generation issues. Download issues otherwise.

**Comment by rkm7232** [comment]
Hi , thanks,
I have generation issues. invoices are empty. download issue has been gone due to the change you commited.

**Comment by Kaian** [comment]
What invoice template are you using? One of the provided in the help section of Invoices templates list?

**Comment by rkm7232** [comment]
Hi, sorry for the late.
I used detailed and basic templates that exist in the list by default
I will test/debug this and update the issue as soon as possible.
thanks.

**Comment by Kaian** [comment]
The problem could be that default templates are empty. We've detected a bug that will be solved in next minor release addressing the problem.

Could you check the output of this mysql query:

```SELECT name, LENGTH(template) FROM InvoiceTemplates WHERE brandId IS NULL;```

Regards

**Comment by rkm7232** [comment]
I think that was the reason,
anyway I made some changes including the one above. and now invoices are fine.

This is the output:
Basic	9392
Detailed	10385

thanks for your help

**Comment by Kaian** [comment]
Good to know, thanks for reporting!
