### ISSUE TITLE
Low Balance Notifications not working

### ISSUE THREAD

**Issue by dsmaldone** [irontec/ivozprovider#1472]
### Description
I've created my own notification for Low Balance and set it into a client Prepaid Balance (Under Prepaid Balances-> List of Balance Notifications).
What I was expecting is when the balance goes below the indicated threshold, a new email would be generated and sent to the customer according to the template.

---

- IvozProvider version: 2.15~2.15.2~20200617.2810~31e

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [X] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
I think the script which is doing this is 
`/opt/irontec/ivozprovider/microservices/balances/bin/sync`

and when executed it generates these lines in user.log file:

```
Jul 31 11:36:51 ex01 php.onError[20599]: request.INFO: Matched route "_". {"route":"_","route_parameters":{"_controller":"kernel:sync","_route":"_"},"request_uri":"http://:/","method":"GET"} []
Jul 31 11:36:51 ex01 php.onError[20599]: security.INFO: Populated the TokenStorage with an anonymous Token. [] []
Jul 31 11:36:51 ex01 php.onError[20599]: app.INFO: Companies balances are about to be synced [] []
Jul 31 11:36:51 ex01 php.onError[20599]: app.INFO: Companies balances are about to be synced [] []
Jul 31 11:36:51 ex01 php.onError[20599]: app.ERROR: Carrier#0 not found [] []
Jul 31 11:36:51 ex01 php.onError[20599]: app.ERROR: Carrier#0 not found [] []
```

### Additional Information
The same behavior happens with the default template, I would like to investigate more if you can point where I can check. Of course, I checked in the database related table and there is no Carrier#0 and I'm not able to understand how it creates those indexes

**Comment by mmadariaga** [comment]
Hi @dsmaldone,

Some balance-related fixes were recently introduced in https://github.com/irontec/ivozprovider/pull/1449.
Could you apply those patches and try it again?

**Comment by dsmaldone** [comment]
Hi @mmadariaga!

It looks like the fix you’ve merged works for “bleeding” while I’m using artemis

Some files you were fixing, are not there in artemis

BR
Danilo

**Comment by mmadariaga** [comment]
You're right, some services have being moved recently, you can find them in library/vendor/irontec/ though:

library/Ivoz/Cgr/Infrastructure/Cgrates/Service/CarrierBalanceService.php ->
./library/vendor/irontec/ivoz-core/Infrastructure/Domain/Service/Cgrates/CarrierBalanceService.php

library/Ivoz/Cgr/Infrastructure/Cgrates/Service/CompanyBalanceService.php ->
./library/vendor/irontec/ivoz-core/Infrastructure/Domain/Service/Cgrates/CompanyBalanceService.php

**Comment by dsmaldone** [comment]
Ok
I’ll give it a try and let you know asap!

Regards
Danilo

**Comment by dsmaldone** [comment]
HI @mmadariaga

Looks like
library/spec/Ivoz/Provider/Domain/Service/Carrier/SyncBalancesSpec.php <https://github.com/irontec/ivozprovider/pull/1449/files#diff-355c207ac329d6546d81c2690162aadc> 

It’s not there on 2.15

Any suggestion here?
Regards
Danilo

**Comment by mmadariaga** [comment]
Hi @dsmaldone,

Don't worry about *Spec.php files, they are just unit test files.

Regards

**Comment by dsmaldone** [comment]
HI @mmadariaga

I see these changes will be released on Aug the 28th

I’ll update the version on that date to check it out!

Thanks

Danilo

**Comment by dsmaldone** [comment]
Hi, @mmadariaga I moved to 2.16 but I'm still not receiving notification on low balances. Is there any way to manually executing the script so I can check logs of what is not working?

**Comment by mmadariaga** [comment]
Sure, set manually Companies.balance value in database above de threshold. Then run microservices/balances/bin/sync or wait a few minutes (It's scheduled to run every 3 minutes). The script will:

- Update database value (library/Ivoz/Provider/Domain/Service/Company/SyncBalances.php)
- Check wether de threshold has been broken (library/Ivoz/Provider/Domain/Service/Company/SearchBrokenThresholds.php)
- Send notification (library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php)

**Comment by dsmaldone** [comment]
well...already tried and seems nothing is generated.
I searched in syslog, supervisor, and user logs

Any suggestions on where I can find logs about this? My threshold is set to 10.00 and my balance is 0.91

No mail generated. All other alerts (traffic report etc) are working

**Comment by Kaian** [comment]
Hi

Any update on this? 

Take into account that the notification is only generated when the threshold is broken. If you set the threshold is set to 10, the notification will only be sent when the balance is over 10 and it decreases below 10.

Regards!

**Comment by dsmaldone** [comment]
Hi!
So I've set threshold to 1.00 and took the balance to 1.02, executed a call and then the balance was reported as  0.99.
I think, as wxpwcted, the system tried to send the notification, but:

`Nov 11 12:40:46 8 php.onError[5125]: request.INFO: Matched route "_". {"route":"_","route_parameters":{"_controller":"kernel:sync","_route":"_"},"request_uri":"http://:/","method":"GET"} []
Nov 11 12:40:46 8 php.onError[5125]: security.INFO: Populated the TokenStorage with an anonymous Token. [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getSubject() on null in /opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php:92
Stack trace:
#0 /opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php(62): Ivoz\Provider\Domain\Service\BalanceNotification\NotifyBrokenThreshold->sendNotification(Object(Ivoz\Provider\Domain\Model\Company\Events\CompanyBalanceThresholdWasBroken))
#1 /opt/irontec/ivozprovider/library/vendor/irontec/ivoz-core/Domain/Service/DomainEventPublisher.php(55): Ivoz\Provider\Domain\Service\BalanceNotification\NotifyBrokenThreshold->handle(Object(Ivoz\Provider\Domain\Model\Company\Events\CompanyBalanceThresholdWasBroken))
#2 /opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Service/Company/SearchBrokenThresholds.php(77): Ivoz\Core\Domain\Service\DomainEventPublisher->publish(Object(Ivoz\Provider\Domain\Model\Company\Events\CompanyBalanceT in /opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php on line 92
Nov 11 12:40:46 8 php.onError[5125]: app.INFO: Companies daily usage are about to be synced [] []
Nov 11 12:40:46 8 php.onError[5125]: app.INFO: Companies balances are about to be synced [] []
`

**Comment by Kaian** [comment]
Well, well, thats different then.

The notification triggered, but the code was unable to retrieve the email subject from the template.

Can you provide the Notification template data of your system by running this mysql queries?

SELECT * FROM NotificationTemplates WHERE type = 'lowbalance';
SELECT fromName, subject, languageId, bodyType FROM NotificationTemplatesContents NTC INNER JOIN NotificationTemplates NC ON NTC.notificationTemplateId = NC.id WHERE type = 'lowbalance';

Regards

**Comment by dsmaldone** [comment]
Second update. POSITIVE FEEDBACK! >> Your hint was very helpful!

I've set the threshold to 1.00 and took the balance to 1.01, executed a call, and then the balance was reported as 0.98. This time I can confirm IT WORKS.
I was not aware that the threshold has to be set before the limit is reached as you just reported. (now is ok and fixed on my side. Done!)

The second issue (mine again) was that I've created a Custom Template for my Brand, but I haven't added content for the Custom Template, thinking the default one would have been taken if my Custom Notification Template was empty. (I hope was clear enough). It may be worth to add a control in this case: if a Custom Templare is created and content it's not added for that Custom template, the default one must be chosen instead of throwing that Error in PHP - PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getSubject() on null in /opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php:92


Thanks for your work and I hope my deug helped here!

**Comment by Kaian** [comment]
Hi @dsmaldone 

Good to know. We will fix the Notification code to avoid selecting a template that has no content for the used language, so this error won't happen again.

Thanks for reporting!
