### ISSUE TITLE
QRcode for gs wave not working

### ISSUE THREAD

**Issue by rallisf1** [irontec/ivozprovider#1646]
### Description
QRcode in client portal not showing

---

- IvozProvider version: 2.18~2.18.0~20210813.3292~6d77687+artemis

- Related sections:
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Browser Console errors
--------------------------------
```
vendor.5771b3e5.js:5 Error: Input mode is invalid for text.
    at o.a.checkInputMode (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:18:1269)
    at o.a.getInputMode (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:18:1487)
    at link (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:18:2051)
    at https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:5:251
    at ga (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:5:308)
    at p (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:26122)
    at h (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:22223)
    at p (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:26071)
    at h (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:22223)
    at h (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:22240) <qr class="pointer ng-isolate-scope" text="QRCode" size="46" correction-level="L">
(anonymous) @ vendor.5771b3e5.js:5
(anonymous) @ vendor.5771b3e5.js:5
ga @ vendor.5771b3e5.js:5
p @ vendor.5771b3e5.js:4
h @ vendor.5771b3e5.js:4
p @ vendor.5771b3e5.js:4
h @ vendor.5771b3e5.js:4
h @ vendor.5771b3e5.js:4
h @ vendor.5771b3e5.js:4
(anonymous) @ vendor.5771b3e5.js:4
(anonymous) @ vendor.5771b3e5.js:14
ga @ vendor.5771b3e5.js:5
p @ vendor.5771b3e5.js:4
h @ vendor.5771b3e5.js:4
(anonymous) @ vendor.5771b3e5.js:4
k @ vendor.5771b3e5.js:14
(anonymous) @ vendor.5771b3e5.js:14
$broadcast @ vendor.5771b3e5.js:6
(anonymous) @ vendor.5771b3e5.js:14
i @ vendor.5771b3e5.js:5
(anonymous) @ vendor.5771b3e5.js:5
$eval @ vendor.5771b3e5.js:6
$digest @ vendor.5771b3e5.js:5
$apply @ vendor.5771b3e5.js:6
f @ vendor.5771b3e5.js:5
q @ vendor.5771b3e5.js:5
v.onload @ vendor.5771b3e5.js:5
load (async)
(anonymous) @ vendor.5771b3e5.js:5
r @ vendor.5771b3e5.js:5
k @ vendor.5771b3e5.js:5
i @ vendor.5771b3e5.js:5
(anonymous) @ vendor.5771b3e5.js:5
$eval @ vendor.5771b3e5.js:6
$digest @ vendor.5771b3e5.js:5
$apply @ vendor.5771b3e5.js:6
f @ vendor.5771b3e5.js:5
q @ vendor.5771b3e5.js:5
v.onload @ vendor.5771b3e5.js:5
load (async)
(anonymous) @ vendor.5771b3e5.js:5
r @ vendor.5771b3e5.js:5
k @ vendor.5771b3e5.js:5
i @ vendor.5771b3e5.js:5
(anonymous) @ vendor.5771b3e5.js:5
$eval @ vendor.5771b3e5.js:6
$digest @ vendor.5771b3e5.js:5
$apply @ vendor.5771b3e5.js:6
(anonymous) @ vendor.5771b3e5.js:4
e @ vendor.5771b3e5.js:4
h @ vendor.5771b3e5.js:4
ga @ vendor.5771b3e5.js:4
fa @ vendor.5771b3e5.js:4
(anonymous) @ vendor.5771b3e5.js:8
l @ vendor.5771b3e5.js:2
m @ vendor.5771b3e5.js:2
setTimeout (async)
(anonymous) @ vendor.5771b3e5.js:2
k @ vendor.5771b3e5.js:2
fireWith @ vendor.5771b3e5.js:2
fire @ vendor.5771b3e5.js:2
k @ vendor.5771b3e5.js:2
fireWith @ vendor.5771b3e5.js:2
ready @ vendor.5771b3e5.js:2
m @ vendor.5771b3e5.js:1
vendor.5771b3e5.js:5 Error: Input mode is invalid for text.
    at o.a.checkInputMode (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:18:1269)
    at o.a.getInputMode (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:18:1487)
    at link (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:18:2051)
    at https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:5:251
    at ga (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:5:308)
    at p (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:26122)
    at h (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:22223)
    at h (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:22240)
    at p (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:26071)
    at h (https://myvoip.dws.gr/scripts/vendor.5771b3e5.js:4:22223) <qr text="QRCode" size="200" class="ng-isolate-scope">
```

### Additional Information
Yes I have enabled the qrcode in the user.

**Comment by Kaian** [comment]
Hi @rallisf1 

Thanks for reporting using provided templates :)

I have tested 2.18.2 in our testing enviroments without problems, the QR is displayed correctly, and 2.18.0 should work too because User portal has not changed in recent releases.

Have you tried with multiple browsers? Chrome, Firefox? All report the same errors?

Regards!

**Comment by rallisf1** [comment]
Yes, both firefox and chrome/edge browsers report the same errors.

**Comment by Kaian** [comment]
I was able to confirm this bug by changing the name of my user to _Ευχαριστώ_

Looks like the QR library has problems with utf8 characteres so anything outside ASCII raises the error.

**Comment by rallisf1** [comment]
Haha, didn't expect that. I changed the user's name to latin characters and it worked.

Thank you for your time.
