### ISSUE TITLE
DDI Provider Registrations can't be deleted

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#726]
This is the stack trace when trying to delete a DDI Provider Registration:

```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined method Ivoz\Provider\Domain\Model\DdiProvider\DdiProviderDto::get() in /opt/irontec/klear/modules/klearMatrix/models/Field/Select/Mapper.php:203
Stack trace:
#0 /opt/irontec/klear/modules/klearMatrix/models/Field/Select/Mapper.php(177): KlearMatrix_Model_Field_Select_Mapper-&gt;_getItemValue(Object(Ivoz\Provider\Domain\Model\DdiProvider\DdiProviderDto))
#1 /opt/irontec/klear/modules/klearMatrix/models/Field/Select/Mapper.php(79): KlearMatrix_Model_Field_Select_Mapper-&gt;_setOptions(Array)
#2 /opt/irontec/klear/modules/klearMatrix/models/Field/Select/Abstract.php(18): KlearMatrix_Model_Field_Select_Mapper-&gt;init()
#3 /opt/irontec/klear/modules/klearMatrix/models/Field/Select.php(18): KlearMatrix_Model_Field_Select_Abstract-&gt;__construct(Object(Zend_Config), Object(KlearMatrix_Model_Column))
#4 /opt/irontec/klear/modules/klearMatrix/models/Field/Abstract.php(80): KlearMatrix_Model_Field_Select-&gt;_init()
#5 /opt/irontec/klear/modules/klearMatrix/models/Field/Abstract.php(344): KlearMatr in <b>/opt/irontec/klear/modules/klearMatrix/models/Field/Select/Mapper.php</b> on line <b>203</b><br />
```

I have not been able to find how to solve it on code.

I found some typos in klear config yaml files too:

```
root@iv2:/opt/irontec/ivozprovider/web/admin/application/configs/klear# grep -rnw . -e '[^ ]*dialosg[^ ]*'
./CarriersList.yaml:214:  dialogs: &carriers_dialosgLink
./DdiProvidersList.yaml:158:  dialogs: &ddiProviders_dialosgLink
./DdiProvidersList.yaml:171:    <<: *ddiProviderAddresses_dialosgLink
./DdiProviderAddressesList.yaml:63:  dialogs: &ddiProviderAddresses_dialosgLink
```

**Comment by Kaian** [comment]
Thanks for reporting!
