### ISSUE TITLE
ivozprovider-recordings.service entered failed state

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#959]
Only for your information, I can't see any problem with recorded files, but ivozprovider-recordings.service says it.

[Context : I have one PBX with recorder enabled. Is working fine, minutes after terminating a call I can see and listen the call into webpanel ]
But ivozprovider-recordings.service is entering to failed state every 3 minutes.

log with new call:
```Apr 13 10:00:11 xxxxxxxxxxxxxxx systemd[1]: Starting IvozProvider Recordings Parser...
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: changelog.INFO: CommandWasExecuted > Unregistered::Unregistered([]) [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: changelog.INFO: EntityWasCreated > Ivoz\Provider\Domain\Model\Recording\Recording#30 > {"callid":"9be53fda-54ff-4c8c-b999-ca5dab2d6768","calldate":"2019-04-13 07:56:54","type":"ddi","duration":28.44,"caller":"+34xxx","callee":"+34xxx","recorder":"+34xxx","recordedFileFileSize":28751,"recordedFileMimeType":"audio\/mpeg; charset=binary","recordedFileBaseName":"xxx.mp3","companyId":1,"id":30} [] []
```

and then:
```
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: request.INFO: Matched route "_". {"route":"_","route_parameters":{"_controller":"kernel:processRtpRecordingAction","_route":"_"},"request_uri":"http://:/","method":"GET"} []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: security.INFO: Populated the TokenStorage with an anonymous Token. [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: app.INFO: [Recordings] Processing 20 files in recording dir /opt/irontec/ivozprovider/storage/ivozprovider_model_recordings.originalfile/  [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx recordings-encoder[14080]: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: Division by zero in /opt/irontec/ivozprovider/library/vendor/debach/zend-mp3/lib/Zend/Media/Mpeg/Abs.php:250
Apr 13 10:00:12 xxxxxxxxxxxxxxx recordings-encoder[14080]: Stack trace:
Apr 13 10:00:12 xxxxxxxxxxxxxxx recordings-encoder[14080]: #0 /opt/irontec/ivozprovider/microservices/recordings/src/Recording/Encoder.php(229): Zend_Media_Mpeg_Abs->__construct('/opt/irontec/iv...')
Apr 13 10:00:12 xxxxxxxxxxxxxxx recordings-encoder[14080]: #1 /opt/irontec/ivozprovider/microservices/recordings/app/MicroKernel.php(47): Recording\Encoder->processAction()
Apr 13 10:00:12 xxxxxxxxxxxxxxx recordings-encoder[14080]: #2 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): MicroKernel->processRtpRecordingAction()
Apr 13 10:00:12 xxxxxxxxxxxxxxx recordings-encoder[14080]: #3 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
Apr 13 10:00:12 xxxxxxxxxxxxxxx recordings-encoder[14080]: #4 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Re in /opt/irontec/ivozprovider/library/vendor/debach/zend-mp3/lib/Zend/Media/Mpeg/Abs.php on line 250
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: app.INFO: [Recordings][08ba51b6] Checking file 9be53fda-54ff-4c8c-b999-ca5dab2d6768-721f0060f52eb0aa-mix.wav  [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: app.INFO: [Recordings][08ba51b6] Encoding to 9be53fda-54ff-4c8c-b999-ca5dab2d6768.mp3  [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: app.INFO: [Recordings][08ba51b6] Create Recordings entry with id 30  [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: app.INFO: [Recordings][5a69776c] Checking file 9e3b26ba-e28f-40d0-bbff-49fa6e63568c-4d6d765d9b542f86-mix.wav  [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: app.INFO: [Recordings][5a69776c] Encoding to 9e3b26ba-e28f-40d0-bbff-49fa6e63568c.mp3  [] []
Apr 13 10:00:12 xxxxxxxxxxxxxxx [14080]: php.CRITICAL: Uncaught Warning: Division by zero {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Division by zero at /opt/irontec/ivozprovider/library/vendor/debach/zend-mp3/lib/Zend/Media/Mpeg/Abs.php:250)"} []
Apr 13 10:00:12 xxxxxxxxxxxxxxx systemd[1]: ivozprovider-recordings.service: Main process exited, code=exited, status=255/n/a
Apr 13 10:00:12 xxxxxxxxxxxxxxx systemd[1]: Failed to start IvozProvider Recordings Parser.
Apr 13 10:00:12 xxxxxxxxxxxxxxx systemd[1]: ivozprovider-recordings.service: Unit entered failed state.
Apr 13 10:00:12 xxxxxxxxxxxxxxx systemd[1]: ivozprovider-recordings.service: Failed with result 'exit-code'.

```
this last is looping during the day.

Inside opt/irontec/ivozprovider/storage/ivozprovider_model_recordings.originalfile/
20 wav files
1 mp3 file

Inside opt/irontec/ivozprovider/storage/ivozprovider_model_recordings.recordedfile/:
31 mp3 files ( separated by dirs)

Regards

**Comment by mmadariaga** [comment]
Thanks for reporting, we'll take a look at it
