### ISSUE TITLE
Not recieving voicemails from PBX

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#986]
2.10~2.10.0~20190430.2009~1db7b82+artemis all
I have tested with two different PBX clients

This is from PBX 1
journalctl
```
May 13 19:34:31 sip.xxxxxxxxxx.net onError[17786]: request.INFO: Matched route "_voicemail_sender". {"route":"_voicemail_sender","route_parameters":{"_controller":"kernel:handleRequestAction","_route":"_voicemail_sender"},"request_uri":"http://localhost/voicemail/sender","method":"GET"} []
May 13 19:34:31 sip.xxxxxxxxxx.net onError[17786]: security.INFO: Populated the TokenStorage with an anonymous Token. [] []
May 13 19:34:31 sip.xxxxxxxxxx.net onError[17786]: php.INFO: User Deprecated: The "Ivoz\Core\Domain\Service\DomainEventPublisher" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Ivoz\\Core\\Domain\\Service\\DomainEventPublisher\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []
May 13 19:34:31 sip.xxxxxxxxxx.net onError[17786]: php.INFO: User Deprecated: Service identifiers will be made case sensitive in Symfony 4.0. Using "voicemail\sender" instead of "Voicemail\Sender" is deprecated since Symfony 3.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Service identifiers will be made case sensitive in Symfony 4.0. Using \"voicemail\\sender\" instead of \"Voicemail\\Sender\" is deprecated since Symfony 3.3. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:516)"} []
May 13 19:34:31 sip.xxxxxxxxxx.net onError[17786]: php.CRITICAL: Call to a member function error() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function error() on null at /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97)"} []
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function error() on null in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: Stack trace:
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: #0 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): MicroKernel->handleRequestAction()
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: #1 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: #2 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: #3 /opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: #4 {main}
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]:   thrown in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php on line 97
May 13 19:34:31 sip.xxxxxxxxxx.net kernel: voicemail-sende[17786]: segfault at 8 ip 00007f8462483e24 sp 00007fff6bba7090 error 4 in mailparse.so[7f846247c000+d000]
May 13 19:34:31 sip.xxxxxxxxxx.net asterisk[9675]: Segmentation fault (core dumped)

```
tested manually as : https://github.com/irontec/ivozprovider/issues/933#issuecomment-477039048
```
/tmp# cat /tmp/phpy0P5TZ | /opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php 
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function error() on null in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97
Stack trace:
#0 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): MicroKernel->handleRequestAction()
#1 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#2 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#3 /opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php on line 97
Segmentation fault
```
I test with ```/tmp# sendmail email@email< phpy0P5TZ ``` and works, so I understant that isn't my postfix

And this from PBX 9

```
May 13 20:03:08 sip.xxxxxxxxxx.net onError[18154]: request.INFO: Matched route "_voicemail_sender". {"route":"_voicemail_sender","route_parameters":{"_controller":"kernel:handleRequestAction","_route":"_voicemail_sender"},"request_uri":"http://localhost/voicemail/sender","method":"GET"} []
May 13 20:03:08 sip.xxxxxxxxxx.net onError[18154]: security.INFO: Populated the TokenStorage with an anonymous Token. [] []
May 13 20:03:08 sip.xxxxxxxxxx.net onError[18154]: php.INFO: User Deprecated: The "Ivoz\Core\Domain\Service\DomainEventPublisher" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Ivoz\\Core\\Domain\\Service\\DomainEventPublisher\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []
May 13 20:03:08 sip.xxxxxxxxxx.net onError[18154]: php.INFO: User Deprecated: Service identifiers will be made case sensitive in Symfony 4.0. Using "voicemail\sender" instead of "Voicemail\Sender" is deprecated since Symfony 3.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Service identifiers will be made case sensitive in Symfony 4.0. Using \"voicemail\\sender\" instead of \"Voicemail\\Sender\" is deprecated since Symfony 3.3. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:516)"} []
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function error() on null in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: Stack trace:
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: #0 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): MicroKernel->handleRequestAction()
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: #1 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: #2 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: #3 /opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: #4 {main}
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]:   thrown in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php on line 97
May 13 20:03:08 sip.xxxxxxxxxx.net onError[18154]: php.CRITICAL: Call to a member function error() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function error() on null at /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97)"} []
May 13 20:03:08 sip.xxxxxxxxxx.net kernel: voicemail-sende[18154]: segfault at 8 ip 00007fbbe2083e24 sp 00007ffc3ad69a20 error 4 in mailparse.so[7fbbe207c000+d000]
May 13 20:03:08 sip.xxxxxxxxxx.net asterisk[9675]: Segmentation fault (core dumped)
```

Exactly the same

Hope to be helpful

**Comment by gil-obradors** [comment]
More info:

From PBX1, just before raising the PHP Fatal error, a mysql ERROR:  (but in PBX 9 not appearing)


```
May 13 20:23:08 sip.xxxxxxxxxx.net /usr/sbin/kamailio[9562]: NOTICE: [1b13482a] Request: NOTIFY 'sip:gilobradors@sip.xxxxxxxxxx.net' (29244 NOTIFY) from 'sip:b1c1t2_gilobradors@sip.xxxxxxxxxx.net' (udp:127.0.0.1:6060) [bd1d22b9-2c77-4ba8-9952-8b959faa3c80]
May 13 20:23:08 sip.xxxxxxxxxx.net /usr/sbin/kamailio[9562]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=<null> AND name='gilobradors' AND domain='sip.xxxxxxxxxx.net'' at line 1 (1064)
May 13 20:23:08 sip.xxxxxxxxxx.net /usr/sbin/kamailio[9562]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
May 13 20:23:08 sip.xxxxxxxxxx.net /usr/sbin/kamailio[9562]: ERROR: sqlops [sql_api.c:456]: sql_exec_xquery(): cannot do the query
May 13 20:23:08 sip.xxxxxxxxxx.net /usr/sbin/kamailio[9562]: INFO: [1b13482a] LOOKUP: t_next_contacts - One contact found for sip:gilobradors@sip.xxxxxxxxxx.net, calling sip:gilobradors@10.17.42.51:5060
```

PBX1 is  one DDI redirected to a one user, and this user , with a 10s timeout, callforward to self voicemail

PBX9 is one DDI redirected to a external filter, with a voicemail redirected because an off time


I can reproduce PBX1, it's happening every call

**Comment by Kaian** [comment]
Could this be duplicated of #933?

**Comment by gil-obradors** [comment]
Yes sorry, 
I thought it was solved, and that it was something else but I see that it is the same error.
It stills fail in my system, I understand with a clean 2.10 install is working?

My apologies

**Comment by Kaian** [comment]
No problem!

Not sure, as we mentioned in the other issue we haven't experienced this problem before in any of our environments. Try sending the /tmp file like we mentioned in #933 to check if the voicemail script works.

I mentioned something related with php-mailparse in the other note too :thinking:

**Comment by gil-obradors** [comment]
Solved, It was a problem with firewall, 25 tcp closed handmade for me , my fault.


Thank you
